db:
  image: mysql
  volumes_from:
    - dbdata
  env_file:
    - ./.env

dbdata:
  image: mysql
  volumes:
    - /var/lib/mysql

app:
  image: piwik
  links:
    - db
  volumes:
    - /var/www/html/config
  env_file:
    - ./.env

web:
  build: nginx
  links:
    - app
  volumes_from:
    - app
  ports:
    - "80:80"

cron:
  image: piwik
  command: cron -f
  volumes_from:
    - app
  links:
    - db
